// @version 1.0.0-S (mn-vault-S) — stamped 2026-06-24
// ─────────────────────────────────────────────────────────────────────────────
// approval.ts — out-of-band human approval for the warm-key daemon (Path B).
//
// The daemon holds warm keys but CANNOT sign until a human approves — per
// signature by default, or within an explicitly-opened batch budget.
//
// THE OUT-OF-BAND CHANNEL IS THE HUMAN. The daemon generates a random PAIRING CODE
// and holds it ONLY in memory (never written to disk). The human reads it off the
// daemon's terminal and TYPES it into `vault-approve` in a separate window. Both
// processes then hold the code in RAM and use it to HMAC/verify verdicts. Because
// the code is never on disk, a background same-UID process cannot read it; to
// forge an "approve" it would have to either guess the code (infeasible: ~40 bits,
// one online attempt per request, each request single-shot) or read another
// process's memory (same-UID memory read — explicitly OUT OF SCOPE, and now the
// ONLY way in). This is the honest boundary, and the claim it supports is true:
// no signature without either a human approval or an out-of-scope memory read.
//
// TRANSPORT: a file queue under ~/.mn-vault/pending/ (portable: macOS/Linux/Windows).
// Queue files carry ONLY the decoded summary + ids + an HMAC — NEVER the seed, any
// key, or the pairing code.
// ─────────────────────────────────────────────────────────────────────────────

import { createHmac, randomBytes, timingSafeEqual } from 'crypto';
import {
  writeFileSync, readFileSync, existsSync, mkdirSync, readdirSync, unlinkSync, chmodSync, renameSync, statSync,
} from 'fs';
import { join } from 'path';
import { homedir } from 'os';

const VAULT_DIR   = join(homedir(), '.mn-vault');
const PENDING_DIR = join(VAULT_DIR, 'pending');

export interface DecodedForApproval {
  purpose: string;
  network: string;
  inputCount: number;
  outputs: { recipient: string; valueAtoms: string; token: string; origin?: string }[];
}

export interface PendingRequest {
  id: string;                 // 128-bit random hex
  sessionId: string;          // = sessionIdFromCode(code); binds request↔this daemon session
  createdAt: string;
  createdMs: number;          // for age display + post-dating check
  digest: string;             // hash of the decoded summary (what will be signed)
  decoded: DecodedForApproval;
}

interface Verdict {
  id: string;
  sessionId: string;
  decision: 'approve' | 'deny';
  digest: string;
  mac: string;                // HMAC(code, id|sessionId|decision|digest)
}

function ensureDir(): void {
  mkdirSync(PENDING_DIR, { recursive: true });
  try { chmodSync(PENDING_DIR, 0o700); } catch {}
}

// ── Pairing code (the human-carried secret). Generated by the DAEMON, in memory. ─
// Crockford-ish base32, grouped for readability, ~40 bits. Never written to disk.
export function generatePairingCode(): string {
  const alphabet = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';   // no I/O/0/1 ambiguity
  const raw = randomBytes(8);
  let s = '';
  for (let i = 0; i < 8; i++) s += alphabet[raw[i] % alphabet.length];
  return `${s.slice(0, 4)}-${s.slice(4)}`;               // e.g. K7Q2-9XPL
}

// A non-secret session identifier derived from the code, used only to bind a
// request to the session that issued it (NOT used as the auth key).
export function sessionIdFromCode(code: string): string {
  return createHmac('sha256', 'mn-vault-session-id').update(normalizeCode(code)).digest('hex').slice(0, 16);
}

export function normalizeCode(code: string): string {
  return code.trim().toUpperCase().replace(/[^A-Z0-9]/g, '');   // strip dashes/spaces/case
}

// Display-safety helpers live in net-ids.ts (shared, daemon-free). Re-export here
// so existing importers of approval.ts keep working.
export { sanitizeForTerminal, groupDigits } from './net-ids.js';

function macFor(code: string, id: string, sessionId: string, decision: string, digest: string): string {
  return createHmac('sha256', normalizeCode(code)).update(`${id}|${sessionId}|${decision}|${digest}`).digest('hex');
}

// ── Daemon startup: wipe any stale queue (AC5 — no replay across restarts). ──────
export function resetQueue(): void {
  ensureDir();
  for (const f of readdirSync(PENDING_DIR)) {
    if (f.endsWith('.req.json') || f.endsWith('.req.tmp') || f.endsWith('.verdict.json') || f.endsWith('.verdict.tmp')) {
      try { unlinkSync(join(PENDING_DIR, f)); } catch {}
    }
  }
}

// ── Daemon side: post a pending request, then await the verdict (fail-closed). ──
export function postPending(req: PendingRequest): void {
  ensureDir();
  // AC3: remove any pre-existing verdict for this id so a pre-planted "approve"
  // cannot be replayed. (ids are 128-bit random, so this is belt-and-suspenders.)
  cleanup(req.id);
  // BG2: write atomically (temp+rename) — twin of writeVerdict — so the approver
  // never reads a half-written request and the human never sees a torn summary.
  const tmp = join(PENDING_DIR, `${req.id}.req.tmp`);
  const fin = join(PENDING_DIR, `${req.id}.req.json`);
  writeFileSync(tmp, JSON.stringify(req), { mode: 0o600 });
  try { chmodSync(tmp, 0o600); } catch {}
  renameSync(tmp, fin);
}

// Validates a verdict against the in-memory pairing code. Fail-closed on anything:
// no verdict in time, wrong id/session/digest, verdict not post-dating the request,
// or bad/forged MAC ⇒ 'deny'.
export async function awaitVerdict(
  code: string, req: PendingRequest, timeoutMs: number, shouldAbort?: () => boolean,
): Promise<'approve' | 'deny'> {
  const verdictPath = join(PENDING_DIR, `${req.id}.verdict.json`);
  const reqMs = req.createdMs;
  const deadline = Date.now() + timeoutMs;
  const sessionId = sessionIdFromCode(code);
  while (Date.now() < deadline) {
    if (shouldAbort && shouldAbort()) { cleanup(req.id); return 'deny'; }   // BG5: prompt cancel (e.g. shutdown)
    if (existsSync(verdictPath)) {
      try {
        // AC3: the verdict must have been written AFTER we posted the request.
        const vStat = statSync(verdictPath);
        if (vStat.mtimeMs + 1 < reqMs) { cleanup(req.id); return 'deny'; }
        const v: Verdict = JSON.parse(readFileSync(verdictPath, 'utf8'));
        cleanup(req.id);
        if (v.id !== req.id) return 'deny';
        if (v.sessionId !== sessionId) return 'deny';     // AC2: must be THIS session
        if (v.digest !== req.digest) return 'deny';       // must be THIS exact tx
        const expect = macFor(code, v.id, v.sessionId, v.decision, v.digest);
        const got = v.mac ?? '';
        if (got.length !== expect.length) return 'deny';
        if (!timingSafeEqual(Buffer.from(got, 'hex'), Buffer.from(expect, 'hex'))) return 'deny';
        return v.decision === 'approve' ? 'approve' : 'deny';
      } catch { cleanup(req.id); return 'deny'; }
    }
    await new Promise((r) => setTimeout(r, 150));
  }
  cleanup(req.id);
  return 'deny';                                          // timeout ⇒ refuse
}

// ── Approver side: list pending for THIS session, write an atomic MAC'd verdict. ─
export function listPending(sessionId: string): PendingRequest[] {
  ensureDir();
  const out: PendingRequest[] = [];
  for (const f of readdirSync(PENDING_DIR)) {
    if (!f.endsWith('.req.json')) continue;
    try {
      const r: PendingRequest = JSON.parse(readFileSync(join(PENDING_DIR, f), 'utf8'));
      if (r.sessionId === sessionId) out.push(r);          // only requests for our pairing
    } catch {}
  }
  return out.sort((a, b) => a.createdMs - b.createdMs);
}

export function writeVerdict(
  code: string, id: string, decision: 'approve' | 'deny', digest: string,
): void {
  ensureDir();
  const sessionId = sessionIdFromCode(code);
  const v: Verdict = { id, sessionId, decision, digest, mac: macFor(code, id, sessionId, decision, digest) };
  // AC4: write to a temp file then atomically rename, so the daemon never reads a
  // half-written verdict.
  const tmp = join(PENDING_DIR, `${id}.verdict.tmp`);
  const fin = join(PENDING_DIR, `${id}.verdict.json`);
  writeFileSync(tmp, JSON.stringify(v), { mode: 0o600 });
  try { chmodSync(tmp, 0o600); } catch {}
  renameSync(tmp, fin);
}

export function cleanup(id: string): void {
  for (const ext of ['.req.json', '.req.tmp', '.verdict.json', '.verdict.tmp']) {
    const p = join(PENDING_DIR, `${id}${ext}`);
    try { if (existsSync(p)) unlinkSync(p); } catch {}
  }
}

export { PENDING_DIR };
